#!/bin/bash
# Create a new bugfix branch from clipboard

clip="$(pbpaste)"
if [[ $clip =~ https:\/\/lulububu\.atlassian\.net\/browse\/([A-Z0-9]+-[0-9]+) ]]; then
    ticketID=${BASH_REMATCH[1]}
else
    echo "Copy Ticket ID first"
    exit 1
fi

old="$IFS"
IFS='-'
description="$*"
IFS=$old

if [ ! -z "$description" ]; then
    branch_name="bugfix/${ticketID}-${description}"
    git checkout -b "$branch_name"
    git push --set-upstream origin "$branch_name"
fi
