#!/bin/bash

installedPhpVersions=$(brew ls --versions | grep -E 'php(@.*)?\s' | awk '{print $1}' | uniq | sort)

for phpVersion in ${installedPhpVersions[*]}; do
    value="{"

    for otherPhpVersion in ${installedPhpVersions[*]}; do
        if [ "${otherPhpVersion}" != "${phpVersion}" ]; then
            value="${value} brew unlink php@${otherPhpVersion};"
        fi
    done

    value="${value} brew link php@${phpVersion} --force --overwrite; } &> /dev/null && php -v"

    echo "${phpVersion}"="${value}"
done
