#!/bin/bash
# Check every repo for uncommitted changes

SEARCH_DIR=${DEV_HOME:=$HOME/development}
VACATION_ALLOWED=1

echo "Search for projects in $SEARCH_DIR"

find "$SEARCH_DIR" -name ".git" -type d -maxdepth 10 | while read repo; do
    DIRECTORY=${repo%.git}

    cd $DIRECTORY

    LULUBUBU_REMOTES=$(git remote -v | grep -i bitbucket.org:lulububu)

    if [[ $LULUBUBU_REMOTES != '' ]]; then
        echo "#### PROCESSING PROJECT [$DIRECTORY]"

        DIRTY_INDEX=$(git diff --shortstat)
        UNPUSHED_CHANGES=$(git log --branches --not --remotes --simplify-by-decoration --decorate --oneline)

        if [[ $DIRTY_INDEX != '' ]]; then
            echo ">>>>>> Project has a dirty index"
            echo "$DIRTY_INDEX"
            echo ""

            VACATION_ALLOWED=0
        fi

        if [[ $UNPUSHED_CHANGES != '' ]]; then
            echo ">>>>>> Project has unpushed changes"
            echo "$UNPUSHED_CHANGES"
            echo ""

            VACATION_ALLOWED=0
        fi
    fi
done

if [[ $VACATION_ALLOWED -eq 1 ]]; then
    echo "🚀 have fun 🎉"
else
    echo "😭 oh oh there are unpushed changes ❌"
fi
